name: Generate images

on:
  push:
    branches: main

jobs:
  docs:
    runs-on: self-hosted
    needs: [ conditional_job_check_files ]
    if: needs.conditional_job_check_files.outputs.docs_changed == 'True'

    steps:
      - uses: actions/checkout@v2
        with:
          filters: |
            workflows:
              - 'device/**'
              - 'device-lowres/**'
              - 'images/**'
              - 'index.js'
              - 'createJsonOutput.js'
              - '.github/workflows/**'

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Install Yarn
        run: npm install --global yarn

      - name: Install dependencies
        run: yarn

      - name: Generate JSON output
        run: node createJsonOutput.js

      - name: Generate images
        run: node index.js

      - name: Create CNAME
        run: echo 'img.appledb.dev' >> out/CNAME

      - name: No jekyll
        run: echo '' >> out/.nojekyll

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: out
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
