name: Generate images

on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  docs:
    runs-on: M1

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Install Yarn
        run: npm install --global yarn

      - name: Install dependencies
        run: yarn

      - name: Generate images
        run: node index.js

      - name: Create CNAME
        run: echo 'img.appledb.dev' >> out/CNAME

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: out
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}