name: Generate images

on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  conditional_job_check_files:
    runs-on: ubuntu-latest
    # Declare outputs for next jobs
    outputs:
      docs_changed: ${{ steps.check_file_changed.outputs.docs_changed }}
    steps:
    - uses: actions/checkout@v2
      with:
        # Checkout as many commits as needed for the diff
        fetch-depth: 2
    - shell: pwsh
      id: check_file_changed
      run: |
        $diff = git diff --name-only HEAD^ HEAD
        # Check if a file under docs/ or with the .md extension has changed (added, modified, deleted)
        $SourceDiff = $diff | Where-Object { $_ -match '^images/' -or $_ -match '^images-lowres/'  -or $_ -match 'index.js' }
        $HasDiff = $SourceDiff.Length -gt 0
        # Set the output named "docs_changed"
        Write-Host "::set-output name=docs_changed::$HasDiff"

  docs:
    runs-on: M1
    needs: [ conditional_job_check_files ]
    if: needs.conditional_job_check_files.outputs.docs_changed == 'False'

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Install Yarn
        run: npm install --global yarn

      - name: Install dependencies
        run: yarn

      - name: Generate images
        run: node index.js

      - name: Create CNAME
        run: echo 'img.appledb.dev' >> out/CNAME

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: out
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
