name: Send submodule updates to parent repo

on:
  push:
    branches: 
      - main

jobs:
  update_dbweb:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with: 
          repository: littlebyteorg/appledb-web
          token: ${{ secrets.PRIVATE_TOKEN_GITHUB }}

      - name: Pull & update submodules recursively
        run: |
          git submodule update --init apple-device-images
          git submodule update --remote apple-device-images
      - name: Commit
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions - update submodules"
          git add --all
          git commit -m "Update apple-device-images submodule" || echo "No changes to commit"
          git push
